<?php
/**
 * COmanage Registry RestDCCDocDB Provisioner Plugin Language File
 *
 * Portions licensed to the University Corporation for Advanced Internet
 * Development, Inc. ("UCAID") under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * UCAID licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @link          http://www.internet2.edu/comanage COmanage Project
 * @package       registry-plugin
 * @since         COmanage Registry v3.2.2
 * @license       Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 */
  
global $cm_lang, $cm_texts;

// When localizing, the number in format specifications (eg: %1$s) indicates the argument
// position as passed to _txt.  This can be used to process the arguments in
// a different order than they were passed.

$cm_rest_dcc_provisioner_texts['en_US'] = array(
  // Titles, per-controller
  'ct.co_rest_dcc_provisioner_targets.1'  => 'RestDCC DocDB Provisioner Target',
  'ct.co_rest_dcc_provisioner_targets.pl' => 'RestDCC DocDB Provisioner Targets',
  
  // Error messages
  'er.restdccprovisioner.restdcc_url'     => 'No RestDCC URL found',
  'er.restdccprovisioner.access_token'   => 'Access token not received',
  'er.restdccprovisioner.state'          => 'State token mismatch',
  'er.restdccprovisioner.institution.notfound' => 'Insititution not found in DocDB database',
  'er.restdccprovisioner.author.query.failed'  => 'Failed to query Author in DocDB database',
  'er.restdccprovisioner.author.update.failed' => 'Failed to update Author in DocDB database',
  'er.restdccprovisioner.author.create.failed' => 'Failed to create Author in DocDB database',
  'er.restdccprovisioner.emailuser.update.failed' => 'Failed to update EmailUser in DocDB database',
  'er.restdccprovisioner.emailuser.create.failed' => 'Failed to create EmailUser in DocDB database',
  'er.restdccprovisioner.remoteuser.update.failed' => 'Failed to update RemoteUser in DocDB database',
  'er.restdccprovisioner.remoteuser.create.failed' => 'Failed to create RemoteUser in DocDB database',
  'er.restdccprovisioner.securitygroup.query.failed' => 'Failed to query SecurityGroup in DocDB database',
  'er.restdccprovisioner.usersgroup.query.failed' => 'Failed to query UsersGroup in DocDB database',
  'er.restdccprovisioner.usersgroup.delete.failed' => 'Failed to delete UsersGroup in DocDB database',
  'er.restdccprovisioner.usersgroup.create.failed' => 'Failed to create UsersGroup in DocDB database',
  
  // Plugin texts
  'pl.restdccprovisioner.restdcc_url'    => 'DCC Server URL',
  'pl.restdccprovisioner.restdcc_url.desc' => 'The URL of the DCC server to be used by this provisioner. The OAuth2 and REST API URLs will be constructed from this base URL.',
  'pl.restdccprovisioner.added'          => 'Added to DocDB Security Group "%1$s"',
  'pl.restdccprovisioner.callback_url'   => 'Callback URL',
  'pl.restdccprovisioner.client_id'      => 'Client ID',
  'pl.restdccprovisioner.client_id.desc' => 'The Client ID given to the DCC OAuth2 Register Client script.',
  'pl.restdccprovisioner.client_secret'  => 'Client Secret',
  'pl.restdccprovisioner.client_secret.desc' => 'The Client Secret generated by the DCC OAuth2 Register Client script after registering this application.',
  'pl.restdccprovisioner.oauth'          => 'After clicking <i>Save</i>, you may be asked by RestDCC to authenticate and/or authorize COmanage in order to continue.',
  'pl.restdccprovisioner.register'       => 'First, register COmanage as an application with the DCC OAuth2 server.<br />
                                            To do this, run the <a href="https://github.com/cosmic-explorer/ce-it-infrastructure/blob/master/dcc/register-client.sh">register_client.sh</a> script from the host running the DCC OAuth2 container.
                                            Choose a Client ID string for this provisioner and enter it below. Pass the Client ID string to the registration script as the argument of the option --client-id and
                                            set the argument of the option --callback-url to be <pre>%1$s</pre>
                                            After registering, enter the Client Secret created by the registration script here.',
  'pl.restdccprovisioner.removed'        => 'Removed from DocDB Security Group "%1$s"',
  'pl.restdccprovisioner.token.none'     => 'No access token has been received, and so provisioning cannot be completed. To obtain a token, please click "Save".',
  'pl.restdccprovisioner.token.ok'       => 'Access token verified and configuration updated',
  'pl.restdccprovisioner.type'           => 'The "DccDocDbID" (case sensitive) Extended Type should be created before using this provisioner. <a href="%1$s">Click here</a> to add it.'
);
